parameters:
    dcs_form_point_form_field.type.class: DCS\Form\PointFormFieldBundle\Form\Type\PointType

services:
    dcs_form_point_form_field.type:
        class: %dcs_form_point_form_field.type.class%
        arguments: [%form_point_form_field.parent%]
        tags:
            - { name: form.type, alias: point }